
<?php
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.hello':
      return '<p>' . t('Hello thusha') . '<p>' ;


}
}

function hello_cron() {

  Drupal::messenger()->addMessage(t("Your Hello function Access Denied"), "error");

}

function hello_user_login(Drupal\User\UserInterface $account) {

  \Drupal::messenger()->addMessage(t('Welcome Dear %name.',['%name' => $account->getAccountName()]));
  //ksm(\Drupal::database());
  \Drupal::database ()->insert ('hello_user_statistics')
    ->fields([
      'uid'=>$account->id(),
      'action'=> '1',
      'time' => REQUEST_TIME,
    ])
    ->execute();

}
function hello_user_logout($account) {
  \Drupal::database()->insert('hello_user_statistics')
    ->fields([
      'uid'=> $account->id(),
      'action'=> '0',
      'time' => REQUEST_TIME,
    ])
    ->execute();

}
