
<?php
use \Drupal\Core\Form\FormStateInterface;
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.hello':
      return '<p>' . t('Hello thusha') . '<p>' ;
}
}

function hello_cron() {

  //Drupal::messenger()->addMessage(t("Your Hello function Access Denied"), "error");
$purge_days_number = \Drupal::config('hello.settings')->get('purge_days_number');
if($purge_days_number !='0'){
  $nombre_supperessions = \Drupal::database()->delete('hello_user_statistics')->condition('time', REQUEST_TIME - $purge_days_number *(24*3600), '<')->execute();

  \Drupal::messenger()->addMessage(t('@nombre_supperessions records have been deleted.',['@nombre_supperessions' =>
    $nombre_supperessions]));
}
}

function hello_user_login(Drupal\User\UserInterface $account) {
  //ksm(\Drupal::database());
  \Drupal::database()->insert('hello_user_statistics')->fields([
      'uid'=>$account->id(),
      'action'=> '1',
      'time' => REQUEST_TIME,
    ])->execute();
  \Drupal::messenger()->addMessage(t('Welcome Dear %name.',['%name' => $account->getAccountName()]));

  $roles =\Drupal::config('hello.settings')->get('role_user_connections');
  $user_roles = $account->getRoles();
  $diff = array_intersect($roles, $user_roles);
  if(count($diff)>'0'){
    \Drupal::database()->insert('hello_user_statistics')
      ->fields([
        'uid' => $account->id(),
        'action' => '1',
        'time' => REQUEST_TIME,
      ])
      ->execute();
  }
}


function hello_user_logout($account) {
  \Drupal::database()->insert('hello_user_statistics')->fields([
      'uid'=> $account->id(),
      'action'=> '0',
      'time' => REQUEST_TIME,
    ])->execute();

}
function hello_theme()
{
  return array(
    'hello_user_connection' => array(
      'template' => 'hello-user-connection',
      'variables' => array('data' => Null,
        'user' => NULL ,
        'count'=>NULL),
    ),
  );
}

function hello_form_user_admin_settings_alter(array &$form,FormStateInterface $form_state){
  $roles_config=\Drupal::config('hello.settings')->get('role_user_connections');
  $roles = \Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();

$options = [];
unset($roles['anonymous']);
foreach ($roles as $key=>$role){
  $options[$key] = $role->label();
}

$form['test']=[
  '#type' => 'details',
  '#title' =>t('Roles for which to collect activity statistics'),
  '#open'=> TRUE,
  '#weight'=>'-100',
];
  $form['test']['roles']= [
    '#type' => 'checkboxes',
    '#options' => $options,
    '#default_value' => $roles_config,
      ];

$form['#submit'][]='hello_form_user_admin_settings_submit';
}

function hello_form_user_admin_settings_submit($form, FormStateInterface $formState){
  $config = \Drupal::configFactory()->getEditable('hello.settings');
  $config->set('role_user_connections',$formState->getValue('roles'))->save();
}
